### ISSUE TITLE
unauthorized

### ISSUE THREAD

**Issue by robinsingh-bw** [snub-fighter/python-bitrue#4]
Hey,

This seems to return unauthorized when calling any of the private endpoints, any idea whats going on?

Thanks

**Comment by firepol** [comment]
@snub-fighter hi you, would be nice to have an answer/follow-up on this.

**Comment by snub-fighter** [comment]
@robinsingh-bw can u provide more info.  Example?

**Comment by firepol** [comment]
@snub-fighter I'm trying to use any bitrue api. I tried also a branch on ccxt and I get this error.
Does the account method work for you, to check your balance? Using curl, I get UNAUTHORIZED.
Using ccxt I get unauthorized. I double checked my api key/secret and it had "Read information (required)" only.
I edited the api key and checked the checkbox for "Trading available". That fixed the "unauthorized".
Wow, what an api, I was thinking that reading permission was enough to actually *read* my account info... nope, it worked only with trading permission. Mystery solved...

**Comment by snub-fighter** [comment]
Excellent.  Sounds like a Bitrue issue not the package.

**Comment by firepol** [comment]
Exactly, I informed bitrue, see: https://github.com/Bitrue-exchange/bitrue-official-api-docs/issues/8

I guess you can close this issue ;)

**Comment by snub-fighter** [comment]
It is a shame.  They dont care about API or trading all that much.  They love their lending platform more.
